linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - gofmt
    - goimports
    - gocritic
    - wrapcheck

linters-settings:
  wrapcheck:
    ignorePackageGlobs:
      - "github.com/charmbracelet/*"
